- bluesky_httpserver/server/tests/conftest.py
- bluesky_httpserver/server/tests/test_http_server.py
- bluesky_httpserver/server/tests/test_http_server_func_scope.py
- bluesky_httpserver/server/tests/test_server.py
Minor changes to unit test code that fix issues unit tests that were discovered after the server code was removed from `bluesky-queueserver` repository.
> Fixed unit tests after the HTTP Server code was removed from `bluesky-queueserver` repository

- .github/workflows/testing.yml
- README.rst
- bluesky_httpserver/server/server.py
- bluesky_httpserver/server/tests/test_console_output.py
- bluesky_httpserver/server/tests/test_http_server.py
- bluesky_httpserver/server/tests/test_http_server_func_scope.py
- Updated the existing API: `/plans/allowed` and `/devices/allowed` are changed from `GET` to `POST`. `/plans/allowed` now accepts an optional parameter `reduced`. If `"reduced": True`, then the simplified version of plan descriptions that could be more convenient for web applications are returned, otherwise full descriptions are returned. Previously the API always returned simplified descriptions.
- New API `/re/runs` (POST), which combines already existing `/re/runs/active`, `/re/runs/open` and `/re/runs/closed`.
- The following API were added: `plans_existing`, `devices_existing`, `permissions_get`, `permissions_set`, `script_upload`, `function_execute`, `task_status`, `task_result`.
> Updating REST API to match RE Manager 0MQ API

- bluesky_httpserver/server/tests/test_http_server.py
Fixed unit tests for `/queue/item/add` API following `bluesky-queueserver` PR https://github.com/bluesky/bluesky-queueserver/pull/217
> Fixed unit test for `/queue/item/add` API

- bluesky_httpserver/server/server.py
- bluesky_httpserver/server/tests/test_http_server.py
- bluesky_httpserver/server/tests/test_http_server_func_scope.py
Changes:
- Created placeholder for `/console_output` placeholder, which accepts the parameter `lines` specifyng the number of lines to return.
- Changed endpoints `/plans/allowed`, `/devices/allowed`, `/plans/existing` and `/devices/existing` back to `GET`.
> Placeholder for non-streaming '/console_output' endpoint

- README.rst
- bluesky_httpserver/server/console_output.py
- bluesky_httpserver/server/server.py
- bluesky_httpserver/server/tests/test_console_output.py
- bluesky_httpserver/server/tests/test_http_server.py
Simplistic implementation of the `/console_output` API. The API accepts optional parameter `nlines`, which defines the number of lines to return. The returned value is structured similarly to other Queue Server API:
```
{
"success": True,
"msg": "",
"text": <payload - console output represented as multiline text string>,
} 
```
> ENH: simple implementation of /console_output

- bluesky_httpserver/server/console_output.py
- bluesky_httpserver/server/server.py
- bluesky_httpserver/server/tests/test_console_output.py
Implementation of `console_output_update` API for monitoring of console output in polling mode.
The new `console_output_update` endpoint accepts required `last_msg_uid` parameter and returns a list of messages and UID of the last message in the buffer. If the internal buffer contains a message with this UID, then the API returns a list of all the following messages. If the UID is not found, then the empty list is returned. If UID is the string `"ALL"`, then the list of all messages contained in the buffer are returned.
In normal operation: first call the `console_output_update` endpoint with random UID or `"ALL"`, for the next calls use `last_msg_uid` returned by the previous calls.
The API is necessary to implement remote monitoring of console output in polling mode.
- …
> New endpoint: 'console_output_update'

- requirements-dev.txt
- requirements.txt
The `requests` package is now only development dependency, so it is moved to `requirements-dev.txt`. The package also needs  to be removed from the feedstock during the next release.
The `requests` package is used only for unit tests.
- NOTE: remove `requests` package from requirements in `bluesky-httpserver-feedstock` before the next release.
> Change requirements: 'requests' is now in 'requirements-dev.txt'

- README.rst
- bluesky_httpserver/server/server.py
- bluesky_httpserver/server/tests/conftest.py
- bluesky_httpserver/server/tests/test_console_output.py
- bluesky_httpserver/server/tests/test_http_server_func_scope.py
Use standard names for environment variables that specify addresses and public key for RE Manager. The following environment variables are supported:
- `QSERVER_ZMQ_CONTROL_ADDRESS` - address of the control socket of RE Manager;
- `QSERVER_ZMQ_INFO_ADDRESS` - address of the socket used for publishing console output;
- `QSERVER_ZMQ_PUBLIC_KEY` - public key for encrypted communication with RE Manager.
The existing keys are deprecated and will be removed in the future.
The environment variable names are consistent with conventions established in PR https://github.com/bluesky/bluesky-queueserver/pull/234
- Implemented support for standard environment variable names. Old names are deprecated and will be removed in the future. The  following environment variables are supported:
- …
> Use standard environment variable names

- README.rst
Mention `/lock`, `/lock/info` and `/unlock` in the README file.
> ENH: mention '/lock', '/lock/info' and '/unlock' API in documentation

- bluesky_httpserver/routers/core_api.py
Minor fix: some 'write' API that did not receive any parameters, now receive an optional `lock_key` parameter, which need to be passed to RE Manager. Now those API are passing the dictionary of the parameters received from the client to the respective 0MQ API calls. 
The modifications to the code do not change the existing functionality of the HTTP Server.
> Pass parameters to API that used to accept no parameters

- bluesky_httpserver/config.py
Minor fix: the parameters `access_token_max_age`, `refresh_token_max_age` and `session_max_age` loaded from `.yml` config file are represented as integers (seconds), while the server code requires that they are represented as `datetime.timedelta` (this is how the default parameters and parameters passed as EVs are represented). Incorrect type results in exception being raised during processing of login requests, which require generating a token. The PR adds the code that converts the parameters to `datetime.timedelta` type before they are passed to the server.
- Proper handling of parameters `access_token_max_age`, `refresh_token_max_age` and `session_max_age` loaded from config YML file.
> Convert 'max_age' parameters from 'int' to 'datetime.timedelta'

- bluesky_httpserver/authenticators.py
- bluesky_httpserver/tests/test_authenticators.py
- requirements-dev.txt
Implementation of non-blocking LDAP authenticator.
- New parameters of `LDAPAuthenticator`: `connect_timeout`, `receive_timeout`.
- `LDAPAuthenticator` is now not blocking the server event loop while waiting for the response from the server.
- `LDAPAuthenticator` now works with the pool of LDAP servers. The parameter `server_address` accepts a string representing a single server or a list of strings representing multiple servers.
> Non-blocking LDAP authenticator

- README.rst
- bluesky_httpserver/app.py
- bluesky_httpserver/config.py
- bluesky_httpserver/config_schemas/service_configuration.yml
- bluesky_httpserver/tests/conftest.py
- bluesky_httpserver/tests/test_server.py
- docs/source/configuration.rst
Added support for passing several parameters in the config YML file. Before the change, the parameters could be passed to the server only using the environment variables:
- `QSERVER_ZMQ_CONTROL_ADDRESS`
- `QSERVER_ZMQ_INFO_ADDRESS`
- `QSERVER_ZMQ_PUBLIC_KEY`
- `QSERVER_HTTP_CUSTOM_ROUTERS`
The respective sections of YML file would look the following:
```
qserver_zmq_configuration:
control_address: tcp://localhost:60615
info_address: tcp://localhost:60625
public_key: ${PUBLIC_KEY}
server_configuration:
custom_routers:
- modu.le1
- mod.ule2
```
- The parameters passed using the environment variables `QSERVER_ZMQ_CONTROL_ADDRESS`, `QSERVER_ZMQ_INFO_ADDRESS`, `QSERVER_ZMQ_PUBLIC_KEY` and `QSERVER_HTTP_CUSTOM_ROUTERS` can now be passed in the configuration YML file.
Existing unit tests were …
> Support for 0MQ and server configuration parameters in the config YML file

- docs/source/conf.py
Remove `scipy` and `pandas` from intersphinx mapping, since it is not used in documentation and connection is unreliable and periodically causes build issues.
> Comment 'scipy' and 'pandas' intersphinx mapping (documentation)

- .flake8
- .github/workflows/testing.yml
- bluesky_httpserver/app.py
- bluesky_httpserver/authorization/__init__.py
- bluesky_httpserver/authorization/api_access.py
- bluesky_httpserver/tests/access_api_server/api_server.py
- bluesky_httpserver/tests/test_access_policies.py
- docs/source/configuration.rst
Implementation of  `ServerBasedAPIAccessControl` access policy. User access data is periodically downloaded from an Access Control server by calling `/instruments/{instrument}/{endstation}/qserver/access` API. Currently communication to Access Control server is unauthenticated. Authentication can be added in the future
See documentation for details.
Access Control server is intended to reduce load to central services such as Active Directory.
Implementation of  `ServerBasedAPIAccessControl` access policy.
Unit tests are implemented.
> Access control based on API Server

- bluesky_httpserver/authorization/api_access.py
- bluesky_httpserver/tests/access_api_server/api_server.py
- bluesky_httpserver/tests/test_access_policies.py
- docs/source/configuration.rst
Some additional modifications to 'ServerBasedAPIAccessControl' access policy. The PR is continuation of https://github.com/bluesky/bluesky-httpserver/pull/47 The changes include:
- User's email is provided in the dictionary with user access information using the key `email` instead of `mail`.
- User access information provided by the external API server now contains `last_name` and `first_name` keys instead of `displayed_name`. The displayed name is generated based on the first and last name of the user.
- `ServerBasedAPIAccessControl` policy is now calling `/instrument/{instrument}/qserver/access` instead of `/instruments/{instrument}/{endstation}/qserver/access`. `ServerBasedAPIAccessControl` policy does not accept the parameter `endstation`.
`ServerBasedAPIAccessControl` is not …
> Modifications to 'ServerBasedAPIAccessControl' Policy

- bluesky_httpserver/routers/core_api.py
- bluesky_httpserver/tests/test_core_api_main.py
New API were added to bring the package up-to-date with the Queue Server:
- `/config/get` API
- `/queue/autostart` API
This PR should be merged with https://github.com/bluesky/bluesky-queueserver-api/pull/41
Add new API that already exist in the Queue Server, but not supported by this package.
- New API: `/config/get` and `/queue/autostart`
Unit tests were added.
> New API: /config/get and /queue/autostart

- .github/workflows/testing.yml
- 2
- bluesky_httpserver/authentication.py
- bluesky_httpserver/routers/core_api.py
- bluesky_httpserver/schemas.py
- bluesky_httpserver/settings.py
- v2
Minor changes to make the code compatible with Pydantic 2. 
The server still works with Pydantic 1. The respective code will be removed once Pydantic 1 becomes obsolete.
Addresses the issue https://github.com/bluesky/bluesky-httpserver/issues/56
- The server is compatible with Pydantic v1 and v2 (recently released).
Test matrix includes tests with Pydantic v1 and v2.
> Compatibility with Pydantic 2

- bluesky_httpserver/authorization/api_access.py
Change the JSON schema to accept `.`, `@`, `-`, and `+`, in usernames.
In our LDAP implementation, our email address can be used in the place of the username, and that includes both `.` and `@` in them. Of course, an email can have other symbols still, but those two cover the vast majority of cases already.
So, to use `DictionaryAPIAccessControl` authorization together with our LDAP-based authentication, this change is welcome. Also, I can't see how accepting those characters could be an issue, though I know next to nothing about that stuff, so please boop me if I'm wrong :slightly_smiling_face: 
Added `.`, `@`, `-`, and `+`, to the allowed character list of `BasicAPIAccessControl` and `DictionaryAPIAccessControl` username validations.
We tested this change in our local test deploy of …
> Support email usernames in API access validation

- .github/workflows/docs.yml
- .github/workflows/docs_publish.yml
- .github/workflows/testing.yml
- bluesky_httpserver/app.py
- bluesky_httpserver/config_schemas/service_configuration.yml
- bluesky_httpserver/database/migrations/versions/722ff4e4fcc7_add_write_scopes_to_default_roles.py
- bluesky_httpserver/schemas.py
- bluesky_httpserver/tests/conftest.py
- bluesky_httpserver/tests/test_console_output.py
- docs/source/conf.py
- docs/source/configuration.rst
- requirements-dev.txt
- start_LDAP.sh
Add support for environment variable `QSERVER_ZMQ_ENCODING`, which sets encoding for 0MQ messages.
- Add support for `QSERVER_ZMQ_ENCODING` environment variable, which sets the encoding for 0MQ messages.
> Add support for 0MQ encoding
